language: node_js

node_js:
  - 8

script:
  - npm run build

deploy:
  provider: script
  script: bash scripts/deploy.sh https://github.com/capistrano/capistrano.git capistrano
  on:
    all_branches: true
after_failure:
  - if [ -f tests/tests.log ]; then cat tests/tests.log; fi
  - echo == End of test log ==