language: node_js

node_js:
  - 8

notifications:
  slack: globant:zGKrzzDV03A8EG1qhEUgeokv
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
script:
  - npm run build

deploy:
  provider: script
  script: bash scripts/deploy.sh https://github.com/capistrano/capistrano.git capistrano
  on:
    all_branches: true
after_success:
  - if [ -f success/success.log ]; then cat success/success.log; fi
  - echo == End of sucecss log ==
after_failure:
  - if [ -f tests/tests.log ]; then cat tests/tests.log; fi
  - echo == End of test log ==