language: node_js

node_js:
  - 8

script:
  - npm run build
notifications:
  slack: globant:zGKrzzDV03A8EG1qhEUgeokv

deploy:
  provider: script
  script: bash scripts/deploy.sh https://github.com/capistrano/capistrano.git capistrano
  on:
    all_branches: true
after_success:
  - if [ -f success/success.log ]; then cat success/success.log; fi
  - echo == End of sucecss log ==
after_failure:
  - if [ -f tests/tests.log ]; then cat tests/tests.log; fi
  - echo == End of test log ==